version: 0.2

env:
  variables:
    REACT_APP_BUCKET_NAME: "$REACT_APP_BUCKET_NAME"
    STACK_NAME: "$STACK_NAME"
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - sam --version
    pre_build:
    commands:
      - sam build
  build:
    commands:
      - sam package
  post_build:
    commands:
      - sam deploy --stack-name $STACK_NAME --capabilities CAPABILITY_IAM --no-confirm-changeset --no-fail-on-empty-changeset
      - export APIGATEWAY_URL=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query "Stacks[0].Outputs[?OutputKey=='ApiGatewayUrl'].OutputValue" --output text)
      - cd react-app
      - echo "REACT_APP_API_GATEWAY_ENDPOINT=$APIGATEWAY_URL" > .env
      - npm install
      - npm run build
      - aws s3 sync build/ s3://$REACT_APP_BUCKET_NAME/

